version: '2'
services:
  wtf:
    build: .
    command:
      - ./run.sh
  # web:
  #   privileged: true
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   expose:
  #     - "4000"
  #   command:
  #   - ./run.sh
